### ISSUE TITLE
Woofy Greet Action isn't working

### ISSUE THREAD

**Issue by abhibhaw** [dscnitrourkela/project-maple#28]
[Reference](https://github.com/dscnitrourkela/project-maple/actions/workflows/greet.yml)

Possible Takes:
- [ ] Remove it
- [ ] Fix It

**Comment by HarishTeens** [comment]
I really wished you had fixed it @abhibhaw 😢 . Lemme take a look 👀

**Comment by abhibhaw** [comment]
Okay @HarishTeens I will check first 🤣
