### ISSUE TITLE
Setup Playstore Deployment

### ISSUE THREAD

**Issue by abhibhaw** [dscnitrourkela/project-maple#38]
- Register app on playstore
- Setup continuous deployment to play store beta channel.
- Triggers on a new release.
- Add signing configuration for release build.
- Add play store SHA-1 and SHA-256 in firebase console.

**Comment by SriramPatibanda** [comment]
@abhibhaw This is done right.

**Comment by abhibhaw** [comment]
I don't think so🙈

**Comment by abhibhaw** [comment]
@SriramPatibanda any updates on this??
